# Generated by Django 4.1.3 on 2022-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bboy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("age", models.PositiveBigIntegerField()),
                ("power", models.BooleanField(default=False)),
                ("bio", models.TextField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
