# Generated by Django 4.1.3 on 2022-11-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bboy", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bboy",
            old_name="bio",
            new_name="skills",
        ),
    ]
